Журавлев Н.В., ИУ5-24М, Вариант 5


Задание:
1.   Выбрать набор данных (датасет), содержащий категориальные и числовые признаки и пропуски в данных. Для выполнения следующих пунктов можно использовать несколько различных наборов данных (один для обработки пропусков, другой для категориальных признаков и т.д.).
2.   Для выбранного датасета (датасетов) на основе материалов лекций решить следующие задачи:
*   устранение пропусков в данных;
*   кодирование категориальных признаков;
*   нормализация числовых признаков.





Получение датасета

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import scipy.stats as stats

FILE_NAME = 'movies_youtube_sentiments.csv'
df = pd.read_csv(FILE_NAME, on_bad_lines='skip', sep=',', comment='#', index_col=False)

Устранение пропусков в данных через удаление пропущенных значений

In [ ]:
print(df.shape)
df = df.dropna()
print(df.shape)

(1105, 18)
(900, 18)


Кодирование категориальных признаков через one-hot encoding

In [ ]:
def one_hot_encoding(data):
    unique_values = np.unique(data)

    count_value = len(unique_values)
    result = np.zeros((len(data), count_value))

    for i, sequence in enumerate(data):
        for j, value in enumerate(unique_values):
            if sequence == value:
                result[i][j] = 1
    return result, unique_values.tolist()


array, name = one_hot_encoding(df['genre'].to_numpy())
print(name)
print(array)

['Action', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime', 'Drama', 'Fantasy', 'Horror', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller']
[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


Нормализация числовых признаков через преобразование Йео-Джонсона

In [ ]:
def diagnostic_plots(df, variable):
    plt.figure(figsize=(15,6))
    # гистограмма
    plt.subplot(1, 2, 1)
    df[variable].hist(bins=30)
    ## Q-Q plot
    plt.subplot(1, 2, 2)
    stats.probplot(df[variable], dist="norm", plot=plt)
    plt.show()

# Необходимо преобразовать данные к действительному типу
df['gross'] = df['gross'].astype('float')
df['gross_yeojohnson'], param = stats.yeojohnson(df['gross'])
print('Оптимальное значение λ = {}'.format(param))
# diagnostic_plots(df, 'gross_yeojohnson')
df['gross_yeojohnson']

Оптимальное значение λ = 0.19626141299062172


<ipython-input-5-603ca371cf2c>:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gross'] = df['gross'].astype('float')
<ipython-input-5-603ca371cf2c>:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gross_yeojohnson'], param = stats.yeojohnson(df['gross'])


0       286.125423
1       206.792632
2       203.115833
3       191.664916
4       240.156381
           ...    
1096    121.891935
1100     87.307162
1101    127.091789
1102    205.985124
1104    141.878250
Name: gross_yeojohnson, Length: 900, dtype: float64